### ISSUE TITLE
Migration: Views

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1259]
**Description**
Migration of Views panel.

**Tasks**
Create a new Views component

**Extras**
design: https://xd.adobe.com/view/8a6b23f1-36b6-4419-5fe3-78a60d7ee17d-fc5a/screen/ee904147-e7a4-4eb1-93d1-c809c00dcf5d/Views

**Comment by dleszcz** [comment]
Hi @paloknapo, 
What do you think about this arrangement?
![screenshot 2018-11-30 at 13 30 57](https://user-images.githubusercontent.com/17221890/49289515-4db01780-f4a4-11e8-9975-5d9e718522b6.png)
![screenshot 2018-11-30 at 13 28 14](https://user-images.githubusercontent.com/17221890/49289511-4983fa00-f4a4-11e8-893d-d5221b3b5c29.png)
_React screenshots_

Instead of moving to separated Adding view?
![screenshot 2018-11-30 at 13 33 49](https://user-images.githubusercontent.com/17221890/49289683-d62eb800-f4a4-11e8-82f0-e152eef8b3aa.png)
_Angular screenshot_

**Comment by carmenfan** [comment]
@dleszcz 
I spoke to Pavol, so here are our thoughts :) :

- The extra padding between the first and last one is very strange.
![image](https://user-images.githubusercontent.com/11945337/49290795-ded0bf80-f49f-11e8-8198-fac695f275d4.png)

- Instead of inline add, can we have it so it scrolls to the bottom of the list, adds a new entry and put it in edit mode and keep the logic to automatically populate a view name, so something like this:
![image](https://user-images.githubusercontent.com/11945337/49291239-87cbea00-f4a1-11e8-9713-9971f0238949.png)

- Can we make the buttons a bit bigger (like the angular style) and invert the save button so it has a green background (like angular)?

- Can we make the `4 Views displayed` message align to the left?

- Can we make the lines extend to the end? 
![image](https://user-images.githubusercontent.com/11945337/49291324-d7121a80-f4a1-11e8-9d50-8db0c401714e.png)
