### ISSUE TITLE
Build on staging branch failed

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1423]
Fix build:
https://travis-ci.org/3drepo/3drepo.io/builds/507796182?utm_source=github_status&utm_medium=notification

**Comment by carmenfan** [comment]
@dleszcz 

Staging is passing, your link is on the issues PR.


Are you sure this is a problem?

**Comment by dleszcz** [comment]
There is no file _visualSettingsDialog.styles.ts_ on this issues branch, and that was wired for me. I noticed that on Issue 1272 PR Travis building the **staging** branch and there are indentation errors. So I fixed this ;)

![Screenshot 2019-03-18 at 13 11 59](https://user-images.githubusercontent.com/17221890/54529193-6ffc7100-497f-11e9-872e-1d722e9d93ae.png)


![Screenshot 2019-03-18 at 13 09 55](https://user-images.githubusercontent.com/17221890/54529073-257af480-497f-11e9-8dd6-cb039d4b31bc.png)

**Comment by carmenfan** [comment]
Visual settings was merged in sometime last week, so the reason why your branch doesn't have it would be because it's not up to date with staging.

the travis PR build staging branch with your PR applied, so what you should probably do is update the branch to latest of staging and make the changes there.

So staging isn't failing, the PR is failing because a new lint rule is imposed in issues. I think it makes more sense to make the changes on issues PR :)

**Comment by dleszcz** [comment]
> Visual settings was merged in sometime last week, so the reason why your branch doesn't have it would be because it's not up to date with staging.
> 
> the travis PR build staging branch with your PR applied, so what you should probably do is update the branch to latest of staging and make the changes there.
> 
> So staging isn't failing, the PR is failing because a new lint rule is imposed in issues. I think it makes more sense to make the changes on issues PR :)

OK, so fixed in https://github.com/3drepo/3drepo.io/pull/1388#issuecomment-474279247
