### ISSUE TITLE
Front end should stick to back end names where feasible.

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1604]
See conversation here:

https://github.com/3drepo/3drepo.io/pull/1603#discussion_r300565944

**Comment by dleszcz** [comment]
Hello, 

I just pushed commit with using backend names od issues & risks properties (_owner_, _created_ and _desc_ instead of _author_, _createdDate_ and _description_)

But we reuse the same presentation component for issues, risks & groups. And if we want it to work as before, we need to change the names in **groups**, because the data naming is not consistent or need changes on the backend (below sample objects in backend responses).

@sanmont3drepo @carmenfan
Decide please which way you prefer.

Sample group:
![sample-group](https://user-images.githubusercontent.com/17221890/61109323-ebc97e80-a484-11e9-81fa-fca5791cd6dd.png)

Sample issue:
![sample-issue](https://user-images.githubusercontent.com/17221890/61109311-e4a27080-a484-11e9-837b-8f5d5e5424e4.png)

Sample risk:
![sample-risk](https://user-images.githubusercontent.com/17221890/61109304-e10ee980-a484-11e9-83f3-58b293ebdafa.png)

**Comment by sanmont3drepo** [comment]
If im correct this is a component that's being reused. For fixing the mismatch of fields you could use 
`description || desc || '(no description)'`

**Comment by dleszcz** [comment]
https://github.com/3drepo/3drepo.io/pull/1660
