### ISSUE TITLE
USER_DOES_NOT_HAVE_AVATAR

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#1729]
### Description
Every new account doesn't have an avatar, however this event is logged all the time when they try and look at their settings

118|3drepo  | error: 2019-10-07T15:10:53.633Z   system  USER_DOES_NOT_HAVE_AVATAR (14) [227234964 ms] place=GET /api/xxx/avatar?1570460855826, httpCode=404, contentLength=117

### Goals

- [ ] Remove useless logging / warning

**Comment by carmenfan** [comment]
This is logged because the front end is calling the API to get the user's avatar, and it's returning a 404 because it doesn't have one. As we are logging all API requests, it kind of make sense for it to be there.

The logging comes from automatically logging all API requests, so i don't think it's a good idea to start picking out special situations where we wish to ignore it.
