### ISSUE TITLE
Review/refactor FileRef

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2012]
### Description
File ref seems a little messy and its responsability unclear. At least we should take a look and see if we should change it.

**Comment by carmenfan** [comment]
This has changed in v5.

There is now a filesmanager service which deals with the files management (e.g. creating refs, talking to external handlers to store the files)

Everything in the codebase should be going through this instead of manging files themselves. `FileRefs.js` is now a thin layer that just represents the schema in database
