### ISSUE TITLE
Shadows do not come through transparent objects (Windows or Glazing)

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2032]
### Description
Shadows no longer come through model elements that represent windows or glazing units. If you cut a section through them, there is still no sun showing through. Glazing units leave a dark shade behind them. If you cut through solid elements, like walls, it works fine. 

### Steps to replicate
- Log in to 3drepo.io
- Open this [Model](www.3drepo.io/viewer/Bogdan_D/a3057500-3e1e-4824-94a4-be96f83ad8fc)
- Activate shadows (Hard or Soft)
- Open views Card and click on the Interior 1 or Interior 2 View
- Notice how dark it is
- Activate clip plane and start cutting from top-down
- Once you cut through the Roof you will see sunlight lines
- Solid elements now show sunlight, but glazing panels still come up as shadows

### Pictures/ Gifs of the error
![Shadows](https://user-images.githubusercontent.com/19904513/81668662-e63e1b80-943c-11ea-8035-63973c4dc109.gif)

**Previously You would see the sun come through**
![Sheffield University 4K Option 2](https://user-images.githubusercontent.com/19904513/81668748-0241bd00-943d-11ea-9bdb-f3c6fc290ff8.jpg)

**Currently it is all dark and shaded**
![image](https://user-images.githubusercontent.com/19904513/81668780-0e2d7f00-943d-11ea-9dc3-02142c637f6e.png)

**Comment by sebjf** [comment]
I've had a look and it seems that this is caused by the generated shadowcaster pass (#pragma addshadow) is not working properly in our custom transparent shader. The Diffuse fallback renders fully opaque shadows, making the environment look dark.

This seems to be an issue with setting up custom surface shaders in general and not specific to our shader. Creating a new surface shader and adding the appropriate pragma's results in the same behaviour...

![image](https://user-images.githubusercontent.com/5058369/82126331-f428cf00-97a3-11ea-998f-ae35216a482b.png)

![image](https://user-images.githubusercontent.com/5058369/82126339-00149100-97a4-11ea-8ecc-602e4adea9a7.png)

and will the fallback off...

![image](https://user-images.githubusercontent.com/5058369/82126350-0c98e980-97a4-11ea-8e4c-4d9021f3b5e7.png)

I will investigate further. We may have to reverse engineer the working shaders to figure out how they're doing the faded shadows and write our own shadowcaster pass.

**Comment by sebjf** [comment]
Something else occurred to me: in that 'working' image above, the glass doesn't cast a shadow at all, so it's not rendered as a shadowcaster. Is this actually preferred? If so that can be enabled by just removing the fallback! @carmenfan what is the preferred behaviour?

**Comment by carmenfan** [comment]
> Something else occurred to me: in that 'working' image above, the glass doesn't cast a shadow at all, so it's not rendered as a shadowcaster. Is this actually preferred? If so that can be enabled by just removing the fallback! @carmenfan what is the preferred behaviour?

Possibly, I think if we can make it look the same as before not a lot of people would complain... @BDavydov ?

**Comment by carmenfan** [comment]
@sebjf  is there a reason why we have that on now?

**Comment by sebjf** [comment]
The fallback? I don't believe so. Previously we used Unity's depth pass, which used the Shadow Caster pass to create the depth. Since (as we can see!) the transparent shader doesn't have a working shadowcaster pass, we specified Diffuse as a fallback in order to use its one.

However, all our code should use our explicit DepthNormals pass now, and I think even the Diff Tool - which is the only part that doesn't - still uses its own (probably the same DepthNormals shader); so we should not need it anymore.

I'll look through Unity's inbuilt shaders to see how their fade works, but in the meantime, my suggestion would be to just turn the fallback off. If something relies on it it's likely to break if we add our own blending showcast anyway so might be good to know about soon if there is a testing cycle coming up?

**Comment by carmenfan** [comment]
@sebjf 
ok, let's turn it off and see!

**Comment by BDavydov** [comment]
> Something else occurred to me: in that 'working' image above, the glass doesn't cast a shadow at all, so it's not rendered as a shadowcaster. Is this actually preferred? If so that can be enabled by just removing the fallback! @carmenfan what is the preferred behaviour?

Hi @sebjf, you are right, I don't think that the object's transparency was affecting the density of the shade. Previously it would allow the shadows to come through if it is a transparent object, currently, transparent objects block the sun. It would be great if we could reinstate the previous arrangement, then at least windows would allow the sunlight to come through. Thanks

**Comment by sebjf** [comment]
@carmenfan @BDavydov OK I have pushed those changes to ISSUE_2032. Let me know how they work out! I have had some success with adding our own shadowcaster pass to a mwe based on the Unity shader source, so hopefully we can add semi-transparent shadows.

**Comment by carmenfan** [comment]
@sebjf  does that also fix the section line not being coloured? or it's not related in any way?

**Comment by sebjf** [comment]
@carmenfan Its related in that its part of the shader, but no the shadowcaster pass not working will not cause that, but they can be fixed at the same time.

**Comment by carmenfan** [comment]
> @carmenfan Its related in that its part of the shader, but no the shadowcaster pass not working will not cause that, but they can be fixed at the same time.

cool, if you can fix it in the same branch i think tha'ts easiest! 😃 thanks!

**Comment by sebjf** [comment]
@carmenfan I have pushed a version of this branch with working translucent shadows. Let me know what you think! 
(You may want to consider adjusting the cascade splits in quality settings, if this kind of model will be typical, to avoid the 'spotlight' effect in certain camera orientations.)

Also, in my version the clip border is drawn on transparent objects, its just not obvious because some of them have the alpha quite low...

![image](https://user-images.githubusercontent.com/5058369/82584706-c3261100-9b8c-11ea-9869-aea28ff976c2.png)

Perahps it was fixed while I was updating the shader? Or is it the same, just not salient enough? We can override the clip border alpha if so.

**Comment by sebjf** [comment]
@carmenfan I have also added the clip border limit we discussed. I have put it in ViewerConfig and exposed it in the settings debug tool, so you can see how it behaves...

![image](https://user-images.githubusercontent.com/5058369/82585622-3419f880-9b8e-11ea-9349-9697041af09f.png)

Let me know if you want it moved, etc!

**Comment by carmenfan** [comment]
> Perahps it was fixed while I was updating the shader? Or is it the same, just not salient enough? We can override the clip border alpha if so.

@sebjf  I think it'd be good to override the clip border alpha so it's at 1 like opaque objects, as it's more about demonstrating the cut 

> @carmenfan I have also added the clip border limit we discussed. I have put it in ViewerConfig and exposed it in the settings debug tool, so you can see how it behaves...

Cool, I'll have a try! thanks!

**Comment by carmenfan** [comment]
@sebjf  just had a look, i think it looks good now! I've commited a change to just override the alpha on the border clip too :)

Thanks!

**Comment by carmenfan** [comment]
@sebjf was just about to merge the code and I saw there's a shadowcaster pass there. Was that a test or do we still need it? (Since I thought you fixed it by not having a shadowcaster pass?)

**Comment by sebjf** [comment]
@carmenfan its a working shadowcaster pass, should you want it! (if you dont you we can leave it in another branch or find a way to disable it in the material). without that pass transparent objects just don't render any shadows, which may be preferable, but means you dont get, e.g. the shadow pattern of the skylight elements with different levels of opaqueness in the example model.

**Comment by carmenfan** [comment]
@sebjf gotcha. In that case I'll leave it be and see what @BDavydov  thinks
