### ISSUE TITLE
Smart Groups Object Count is based on our Object IDs not element GUIDs

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2108]
### Description
Model Groups provide incorrect object count. 
In this example, I have 12 Windows of Family type "FE - Dachfenster". When I create a smart group it comes up as 48 objects for Revit, Navisworks & IFC Files. 
In Naviswork model's tree structure, you can see that each Window contains up to 4 child elements. When users query Smart Groups results in 3D Repo or using APIs, they get false object count. It would be great to be able to group those objects based on their GUIDs ie. List Unique GUIDs.
If I perform an API call for List All Metadata and filter for these 12 Windows, I get 48 objects for Revit file. However, when I create the same API call for Navisworks or IFC models, I can group these results based on unique GUIDs. Therefore, I am able to get a true count of windows = 12.

### Steps to replicate
- Upload the same model in 3 file formats Revit, NWC & IFC
- Create a Smart Group for each file format
-  Compare the object count results

### Pictures/ Gifs of the error
**Windows Schedule in Revit**
![Revit Windows](https://user-images.githubusercontent.com/19904513/87534955-a4c12b00-c68e-11ea-9d4e-e48832093ce6.png)

**FE - Dachfenster Windows Smart Group**
![Windows Smart Group](https://user-images.githubusercontent.com/19904513/87535021-bd314580-c68e-11ea-9eff-4728c212a32d.png)

**Each Windows contains 4 Objects**
![Window Smart Group](https://user-images.githubusercontent.com/19904513/87535072-cc17f800-c68e-11ea-91d5-bc63946c7be7.png)
![Window Parts](https://user-images.githubusercontent.com/19904513/87535095-d4703300-c68e-11ea-853f-469bf540b62f.gif)

**Windows from Navisworks**
![Window Navisworks](https://user-images.githubusercontent.com/19904513/87535116-df2ac800-c68e-11ea-885e-fb01a8eab9b6.png)

**Windows from IFC**
![Window IFC](https://user-images.githubusercontent.com/19904513/87535135-e6ea6c80-c68e-11ea-9911-36e39cd0bc69.png)

**Comment by carmenfan** [comment]
@mosment3DRepo @BDavydov 
That's not really a bug, it's a long known problem that is difficult to fix. Determining what is an object is difficult.

we can display the unique IFCGuid of metadata that has matched, but that's also not accurate as you could be satisfying a match high up in the tree which causes the children to be highlighted.

E.g. if I go to the extreme and do `IFC Type = IFCSite`, the root node of the submodel is satisfied so we're highlighting every object in the model. under your suggestion it'd be 1 object instead of every object. To do exactly what you want the front end needs to understand what is an object instead of a mesh and it doesn't. 

We also don't have any sort of wiring to recognise Revit ID, and we can't guarantee anything uploaded from navis has any sort of IDs either.

To do this properly we need to introduce some sort of understanding of what is an object, as that is the only point where we have this info when we import so we can relay this info into the tree on the front end. This really isn't a bug fix kind of situation, it's a feature that needs to go into backlog. It will require bouncer changes as well as BIM file data changes.

**Comment by mosment3DRepo** [comment]
@carmenfan following on from your earlier comment, this has come back up again.

Are we able to skip the bouncer work by saying that the child tree element is the object that needs to be counted?

For example this model (https://www.3drepo.io/viewer/mid_group/a2bcfef0-1ebd-11ec-8aef-c5fb8f858bbf use support credentials) has a smart group which is counting each object double:

![image](https://user-images.githubusercontent.com/62879582/135476526-51cdf677-3814-495b-bc35-5f517045c239.png)

In the tree there are 6 child objects that pass the rule, but the object count is 12 because each one seems to contain 2 meshes:

![image](https://user-images.githubusercontent.com/62879582/135476419-3a1e3b0b-6b37-4c4b-b5f5-c31eca3a11ab.png)

**Comment by carmenfan** [comment]
@mosment3DRepo  This has nothing to do with bouncer. If the metadata match is of a transformation node, io has to traverse all the way down to get the meshes shared_ids  in order to give you the list of shared_ids to operate on in the viewer.

And that count you see on the UI is just the length of shared_ids essentially.

What might be a better representation could be that we give you a count of number of metadata matched. in the query. But even then @miadibe has found cases where we have multiple metadata matches due to them all having the same IFC GUID. 

The problem is we support way too many file formats, so we don't have a concept of foreign unique ID. To properly fix we need to rework the importer - instead of a graphical representation (transformation & meshes), we have the idea of elements & composite element (like navis). And we essentially count elements, as that is the only place we know about how meshes are grouped.

**Comment by mosment3DRepo** [comment]
@carmenfan I think I might've not explained my thought well. What I was thinking is that we already have a Unique elements concept in 3D Repo, which is whether it exists in the Tree in the UI, so I don't think we need to make any changes to the importer unless my theory is too resource costly. In the example below we have 2 meshes which have their own metadata and they both get counted by a smart group:

![image](https://user-images.githubusercontent.com/62879582/135587054-afd49203-7ffc-40e6-880f-c01cfe653d6c.png)

But, in the Tree UI we don't see the individual meshes we only see the parent element which is the actual thing we're trying to count. So is it not possible to query all the meshes and then find out how many unique tree nodes there are and use that number.
![image](https://user-images.githubusercontent.com/62879582/135587287-a9d955e1-707f-46ce-9706-0bf878d418c4.png)

In this instance I can't select each of the meshes individually, just the 'transformation' level which is the same as the tree node

**Comment by carmenfan** [comment]
@mosment3DRepo meshes can also be visible on the tree, it's not necessarily true that the first transformation node above the mesh would represent the true count.

But yes we could potentially go to the tree and count by the first named tree node. Not sure if there will be any edge cases where this doesn't work, but it probably does get you closer to the number you're after.

But note that this would be a pure front end logic change, so anything outside of 3drepo.io (e..g powerBI) would have to do that themselves.

**Comment by mosment3DRepo** [comment]
> @mosment3DRepo meshes can also be visible on the tree, it's not necessarily true that the first transformation node above the mesh would represent the true count.

I think that's OK since at least that way everything adds up in 3D Repo and we can say as long as the tree makes sense the counts will make sense.

Shall I just reopen this ticket or create a new one?

**Comment by carmenfan** [comment]
@mosment3DRepo just reopen the ticket is fine.

Probably need to go into the product triage as well unless it's something super urgent and needs to be dealt with immediately?
