### ISSUE TITLE
typedoc is not compatible with the typescript version we're using

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2175]
if you try to run `yarn docs` it's throwing an error, this is due to :
![image](https://user-images.githubusercontent.com/11945337/92719479-164dea80-f35b-11ea-8328-24b13f52cfc8.png)

We need to upgrade typescript and ensure everything still works fine

**Comment by m1chalkubiak** [comment]
Hi @carmenfan 
I got acquainted with the changes that have been made to typescript from version 3.7.x (which we have had so far) to version 4.0.3 which is the latest version available.
It seems that upgrading to this version should not have any negative impact on the application, because most of the changes introduced in the meantime are additional improvements that do not drastically change the way the language works so far.
Despite version 4, at the beginning of the numbering we can find the information that:
```
With TypeScript 4.0, there are no major breaking changes.
```
I mainly base my conclusions for this article
https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#whats-new

In fact, after updating, typescript found several potentially problematic references that I agree with and which I have corrected.

Of course, I checked `yarn docs` and it works fine.

**Comment by carmenfan** [comment]
@m1chalkubiak cool. If you think it's all fine then just make a PR :)

I spoke to @sanmont3drepo he said he also upgraded materialui core when he tried, and this is probably where the problems were.

We would like to upgrade that too in the near future, but probably best to get Synchro out of the way first as that introduced a lot of UI changes and we don't want the upgrade to be done in parallel

**Comment by m1chalkubiak** [comment]
@carmenfan sure, I can imagine that upgrading `material-ui` in our project could be problematic and time-consuming but it would be worth doing.

PR created.
