### ISSUE TITLE
Kanban Board shows No Image

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2232]
### Description
When User has a kanban board open & someone updates the screenshot in the viewer it comes up as No Image.

### Steps to replicate
- Open Kanban Board
- Load any model with risks
- In another browser tab open the same model
- Edit the viewpoint & screenshot of a Risk
- Notice that in Kanban board it has changed to No Image

### Pictures/ Gifs of the error
![Kanban Screenshot Change](https://user-images.githubusercontent.com/19904513/94782625-68ff4d00-03c3-11eb-9c96-021a051a7c0f.gif)

**Comment by m1chalkubiak** [comment]
Hi @Charence @sanmont3drepo I would need help from either of you.

After a deep digging into the app, I've made "fix" in `update` method of Ticket class on the backend side, but as You can see I'm removing the whole `viewpoints` property from the data object and I'm adding the two properties from `updatedTicket`. In general, this is how the data should look like in case of viewpoint update for FE to update everything properly, but it is very difficult for me to understand why this method creates `viewpoints` property in this way and for what it was needed before. Because now that I removed it, I cannot see any negative effects on the operation of the application, and I don't know whether it is some old unremoved code or something that is needed in some other cases that I'm not aware of.

**Comment by carmenfan** [comment]
@m1chalkubiak  
Sorry didn't realise it was a backend issue!
@Charence  had a look, what you did make sense and should be fine, thanks!

**Comment by m1chalkubiak** [comment]
@carmenfan To be honest, most of the time, while digging around in this issue, I also thought we were doing something wrong with those data that came to us on FE side.
@Charence If you could re-check what exactly we should do with lines 215-269 and 280-287 in `backend/models/ticket.js` Currently I overwrite most of the this that happening there, but not all of them.

**Comment by m1chalkubiak** [comment]
@Charence @carmenfan I see that we have forgotten about it a bit, should I make a PR out of it, and then you will check again if everything works properly here?

**Comment by carmenfan** [comment]
@m1chalkubiak from what I remember about this, Charence had a look and thought it was fine.

By all means make a PR and we can do a final check
