### ISSUE TITLE
Rotating of the model is blocked by the title image

### ISSUE THREAD

**Issue by har00n-haider** [3drepo/3drepo.io#2242]
### Description
See gif

### Steps to replicate
See gif

### Pictures/ Gifs of the error
![rotating issue](https://user-images.githubusercontent.com/72197495/95329494-ef71ce00-089e-11eb-91cf-6f254fa97918.gif)

**Comment by carmenfan** [comment]
There's a transparent div across that strip where the logo, top right menu sits, which is why the viewer doesn't respond:
![image](https://user-images.githubusercontent.com/11945337/95361938-48545d00-08c5-11eb-95f4-c760ad3891cd.png)

I don't think it's worth recoding the way it's structured to gain that 74 pixels of mobility back. Perhaps something to consider on the revamped design? @3drepo/product-team 

I'm going to close this as it's probably a bit of a niche edge case, probably something not worth delving into unless @3drepo/product-team  says otherwise (in which case, feel free to reopen!)
