### ISSUE TITLE
Pause Rendering not being applied

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2257]
### Description
When idling in 3D Repo it doesn't seem as though the Unity game is paused

### Steps to replicate
- Open model
- Open statistics
- See that FPS can change even when nothing is happening

### Pictures/ Gifs of the error

![Pausing](https://user-images.githubusercontent.com/62879582/97002104-64950280-1531-11eb-837c-9a7bb8843d07.gif)
![Pausingzoom](https://user-images.githubusercontent.com/62879582/97002214-97d79180-1531-11eb-863c-bb26044c3fc7.gif)

**Comment by carmenfan** [comment]
@mosment3DRepo 

@sebjf knows more about this and can give you a better explanation

As I understand it, we don't actually pause unity, we just stop the camera from rendering the models. So there are still some skeleton scripts running (navigator, messageParsers etc which needs to listens to the input), so it's not like the whole thing is frozen, only the model is "frozen". The stats generating script falls in that skeleton script family, which is why you can see slight deviation in the numbers. 

Is this a big concern? The numbers should never drop super low to the point where it's comparable to rendering the model.

**Comment by mosment3DRepo** [comment]
Just curious, if I use UnityUtil.pauseRendering() it causes a complete pause of all activity so I assumed the feature was not working

**Comment by carmenfan** [comment]
@mosment3DRepo pause rendering is a different feature to pause rendering when idle,

It predates the pause rendering when idle feature, and it was used for when you're making screenshots (that also uses webgl so it cause massive lag previously). it literally puts a screenshot over the game and disable everything. it's really designed to pause the game whereas the pause rendering when idle is more of a performance optimisation

I appreciate the wording is similar and is crazy. but i'm sure you're used to it... 👍

**Comment by carmenfan** [comment]
Going to close this as it doesn't sound like there's an action needed here? re-open with what you want changed if that's not the case
