### ISSUE TITLE
Risk becomes inaccessible after updating its risk in Kanban Board

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2326]
### Description
When I use Kanban Board, it's missing the Unmitigated Column. If there is a risk already, I can drag other across to update their status to Unmitigated. Unfortunately, they disappear and I can't find them. If I find them again, I can't open them, they give me a white screen in both Kanban Board & Model Viewer. As a result, I can no longer access that risk or change anything attributed to it.

### Steps to replicate
- Open the Kanban Board and change it to show: **Risks** Group by: **Mitigation Status**
- Update a Risk card to Unmitigated
- Open the recently updated Risk
- White screen appears

### Pictures/ Gifs of the error
**Problem 1**
Unmitigated status doesn't exist as a column (whilst other empty columns are present)
![image](https://user-images.githubusercontent.com/19904513/100654986-8bb9cd80-3342-11eb-8486-f08cc4faa7dc.png)

**Problem 2**
Changing the Risk status to unmitigated makes it disappear
![Update Unmitigated Risk](https://user-images.githubusercontent.com/19904513/100655423-29ad9800-3343-11eb-9544-7bd4ad2ce01d.gif)

**Problem 3**
After updating the risk's status to Unmitigated I can no longer open it & change it back. _White screen_
![Risk Open fail](https://user-images.githubusercontent.com/19904513/100656440-a68d4180-3344-11eb-87b5-bfa153e83e31.gif)
![Open Risk Fails](https://user-images.githubusercontent.com/19904513/100656453-ab51f580-3344-11eb-9882-b5b06ea1e6d0.gif)

**Problem 4**
Mitigation Status contains a key-value "_mitigation_status_", should be "_unmitigated_"
![image](https://user-images.githubusercontent.com/19904513/100656857-4a76ed00-3345-11eb-89bb-e51814bc0d67.png)

#### Migration script:
`fixMitigationStatus.py <mongoURL> <mongoPort> <userName> <password>`

**Comment by m1chalkubiak** [comment]
Hi @carmenfan 
I added a fix in a place that was assigning a non-existent value to the `mitigation_status` field and added a handler that in case of risks with old wrong value will not crash the form.

However, since the bug has been around for a while on the production version of the application, we now can have many risks with an incorrect value for this field. Is it possible to make migration of the database so that all incorrect values of this field would be changed to the correct one?

> **Problem 4**
> Mitigation Status contains a key-value "_mitigation_status_", should be "_unmitigated_"

From what I can see in the code and arrangements with SafetiBase v3 unmitigated status of mitigation_status field is correlated with '' (empty string value), is this should be changed according to Bogdan suggestion?

**Comment by carmenfan** [comment]
@m1chalkubiak I've got @Charence to look into the db migration script.

As discussed, we need the following:

- A db migration script to check if there is any risk with `mitigation_status` set to `mitigation_status`, then set it to empty string.
- if we can also add a check to on POST/PATCH request to see if the status is something we recognise, that would be useful too.
