### ISSUE TITLE
Admin API

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2335]
### Description

Admin API Overview

Utilise MongoDB Roles to create an additional level of permissions for tasks that require higher privileges
Create a number of new endpoints to support administrative tasks

### Goals

- [x] #2872
- [ ] #2873
- [ ] #2874
- [ ] #2875
- [ ] #2877

**Comment by carmenfan** [comment]
a few thoughts:

teamspace is teamspace, user account is user account. I know it's a bit merged at times, but we're trying to make a clear distinction going forward.

for e.g. password/email verification etc should be done should be done with an endpoint that actions around users, subscriptions should be done under an action around teamspace.


> get teamspace memberships and permissions

I'm not sure if we want to do this. This may be going a bit too far and actually reading in user data a bit. unless @3drepo/product-team  specifically asked for it?

> manually verify teamspace

I don't think we want to do this, We want the ability to resend verification, and getting the url link to the verification (so we can manually resend to bypass any problems with system email)

> Establish administrative API key configuration

I think we just need to flag users as admins (a bit like the VR Enabled flag), then it can just go through the same authorisation pipeline with an extra check instead of making something special

>![image](https://user-images.githubusercontent.com/11945337/101020982-2e529600-3567-11eb-918c-d9aea9c8035d.png)

This isn't very conventional if that's how you plan to design the endpoint. actions (view/update/reset) are usually represented by HTTP verbs (GET/PATCH/PUT/POST/DELETE etc) . E.g. updating and viewing the subscription should have the same endpoint, with different HTTP Verbs.

@3drepo/product-team you may want to have a look at this and make sure you have everything you need for support.
@anorrie you'd probably also want to see if this is sufficient for sales teams too

**Comment by mosment3DRepo** [comment]
> get teamspace memberships and permissions
If we just go with teamspace that is probably the right level, that will allow support to understand if someone has received an invitation etc. @carmenfan is right that permissions is probably too granular

**Comment by carmenfan** [comment]
Just a few more thoughts as I was adding info here:

>  Establish administrative API key configuration (for initial admin account for platform)
>  Add user to Admin API authorisation

We probably don't want to overcomplicate this. we could just have a flag on individual accounts to indicate whether they're super user (A bit like here maps enabled etc). So they can just utilise their original API keys, and have a function in middleware to determine whether they have admin API access. We probably don't want to create yet another grouping of access permissions and store it differently.

@keifgwinn   probably good to fully fledge out the tasks and endpoints (bit like what Charence did [here](https://github.com/3drepo/3drepo.io/issues/2489)) So we are clear on a conceptual level what the plan is before getting deep into coding! I know we haven't started this but since it's the Q3 focus I thought I'd mention!

**Comment by mosment3DRepo** [comment]
A couple more to throw in if they are feasible:

- [ ] Review list of failed models per teamspace with failure details
- [ ] View current model processing queue across all teamspaces (to be able to see the current backlog and understand if there is a reason models are queued for a long time)
- [ ]

**Comment by keifgwinn** [comment]
> * [ ]  Review list of failed models per teamspace with failure details
This starts getting into seeing the data, which we've decided we'll ask customers to invite support to the teamspace and then they can view all the messages/status as required and remove themselves at the end

> * [ ]  View current model processing queue across all teamspaces (to be able to see the current backlog and understand if there is a reason models are queued for a long time)

We currently have a system level view present of this in internal documentation monitoring the rabbitmq queues

**Comment by carmenfan** [comment]
closing - too many things have changed since - we will need to rescope.
