### ISSUE TITLE
Tree for IFC

### ISSUE THREAD

**Issue by camden-kid** [3drepo/3drepo.io#235]
Make the tree card workable with IFC data.

**Comment by carmenfan** [comment]
found a bug with the visibility states just now. Thought I'd log it here:

1. hidea geometry, with siblings:
![image](https://cloud.githubusercontent.com/assets/11945337/17324604/40bf2de8-589f-11e6-9ed2-6040e05a26fa.png)

2. collapse the parent
![image](https://cloud.githubusercontent.com/assets/11945337/17324614/50bf697e-589f-11e6-91be-fff2356a505b.png)

3. expand the parent again. And now its siblings are also partially hidden even though none of the siblings/off springs of siblings are hidden.
![image](https://cloud.githubusercontent.com/assets/11945337/17324630/627ae6b6-589f-11e6-813a-f2f28a9659af.png)

4. if I unhide the geometry, the whole tree should go back into fully visible state, but it doesn't:
![image](https://cloud.githubusercontent.com/assets/11945337/17324673/8d6d3248-589f-11e6-926f-4b9be0035a8d.png)

**Comment by carmenfan** [comment]
Another one:

1. Hide the entire model, then unhide a single object:
![image](https://cloud.githubusercontent.com/assets/11945337/17325017/39bcf5be-58a1-11e6-8a51-dccfa3d7f8f3.png)

2. Click on the object, the visibility icons have been reset even though the visibility state remained the same.
![image](https://cloud.githubusercontent.com/assets/11945337/17325030/47d81c32-58a1-11e6-8afc-f29fee86d8eb.png)

**Comment by carmenfan** [comment]
And another! :)

1. Click on an object on the model, some components are shown as expanded even though they aren't

![image](https://cloud.githubusercontent.com/assets/11945337/17325344/f00cd504-58a2-11e6-8c49-19a51a30d71f.png)

This bug seems a little non deterministic, only seems to happen on some geometry

**Comment by carmenfan** [comment]
@paloknapo we need to make sure we put these test cases into target process( when we do test case meeting/ whenever you're bored enough :P ) so these bugs are gone when we release

**Comment by carmenfan** [comment]
Bug related to filter:

1. hide the whole model
![image](https://cloud.githubusercontent.com/assets/11945337/17326242/f6568be4-58a7-11e6-99cf-1417ac14536e.png)

2. search for something, and they are all shown as visible.
![image](https://cloud.githubusercontent.com/assets/11945337/17326252/06730fac-58a8-11e6-8a5b-dc432dadfcc2.png)

**Comment by carmenfan** [comment]
Highlighting a metadata object on the search doesn't do anything. Whilst it make sense since it has no geometry, but maybe it needs to at last bring up the metadata card? I'm not sure whether it's even worthwhile having it on the list though, since the metadata is accessible via the mesh object. @PavolKnapo ?
![image](https://cloud.githubusercontent.com/assets/11945337/17328889/f739c700-58b7-11e6-9886-19cfe48b214f.png)

**Comment by carmenfan** [comment]
### Hiding Geometry by default
I tried adding `toggleState` field, set to `"invisible"`. It didn't do anything. Looking at the tree code on the front end it looks like it's not expecting a visibility field on the json tree so I guess some work will need to be done on that side to make it work

So instead I added a boolean field, `hiddenOnLoad`, to determine if the geometry should be loaded initially(if the field doesn't exist it means the geometry should be visible). Since you'd need to do some wiring up anyway I'd much rather use a boolean instead of a string to be more robust. If that's a problem let me know and I'll change it.

````js
{  
   "account":"ifcTest",
   "project":"envelope2",
   "name":"RDS0001 (IFC Space)",
   "path":"41946614-11e2-4d63-aa65-bac82716239b__c7719070-8233-41da-a097-9500526529b4__e52b599d-3477-4ce9-a1ad-5813aca47124__6db5b5e8-58f3-41c1-8c7f-52df4edaa80d__ee303cbe-1eae-4a9b-9b03-23938536c848",
   "_id":"ee303cbe-1eae-4a9b-9b03-23938536c848",
   "shared_id":"dac25a17-aabe-4b1e-a470-f457d12c6cb3",
   "hiddenOnLoad":true
}
````
