### ISSUE TITLE
4D Risk in URL parameter causes browser to white screen

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2433]
### Description

Opening a 4D risk from a URL causes the screen to go white

- This is happening in: prod

### Steps to replicate
- Open this model link with the 3D Repo support account: [https://www.3drepo.io/viewer/Multiplex/bba7f2f0-51a2-11eb-895f-adff9a52627d?riskId=472ff500-5597-11eb-9184-710255f64744](https://www.3drepo.io/viewer/Multiplex/bba7f2f0-51a2-11eb-895f-adff9a52627d?riskId=472ff500-5597-11eb-9184-710255f64744)
- Notice that it crashes

**Comment by carmenfan** [comment]
Passing this onto @sanmont3drepo. The problem is `Cannot read property '2d7837d7-a293-4094-95fc-7033b5a09efe' of undefined` here:
![image](https://user-images.githubusercontent.com/11945337/106147223-85dc3f00-616f-11eb-8a43-14918377491a.png)


  the problem stems from the risk viewpoint has an animation transformation. When it tries to load the viewpoint it's trying to fetch the Ids by calling `selectGetNodesIdsFromSharedIds`, but the tree hasn't been initialised so `nodesBySharedIds` is undefined.

This needs to wait until the tree is ready before acting on it
