### ISSUE TITLE
print doesn't work on terms and conditions

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2530]
### Description
If you try to print the terms and conditions page on prod, it only gives you 1 page and cuts off the rest of the content

We should also check the privacy/cookies policy prints the full content as well

### Steps to replicate
- go to T&C page
- try to print via ctrl + P

### Current Behaviour
- It only prints the first part of the T&C
![image](https://user-images.githubusercontent.com/11945337/111303487-7eec8b80-864c-11eb-901e-0e4f3b045711.png)

### Expected Behaviour
- The entire T&C should be available for print

**Comment by Charence** [comment]
Also use latest notices: https://github.com/3drepo/DevOps/issues/156

**Comment by Charence** [comment]
This problem is fixed by removing a global `overflow: hidden` that was added here: https://github.com/3drepo/3drepo.io/commit/0ab855cdaa5d9acfd7a1a691c0c3582290ca2833#diff-d132fa6dd40ab23521bd50d1d2c04fc75e34a5e4929b26f976f35da7dcbec22fR24

That commit was from the Kanban board. I've checked the Kanban after removing the style and it doesn't seem to be affected, but this should be double checked.
