### ISSUE TITLE
PH for IFC parameter testing

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2594]
place holder branch to deploy a version to test https://github.com/3drepo/3drepobouncer/pull/467

**Comment by BDavydov** [comment]
@carmenfan @mosment3DRepo 
[Federation in 3D Repo](issue-2594.dev.3drepo.io/viewer/Bogdan_D/820b1b70-b7e2-11eb-bb49-9f437c14ef74)
[Original IFC Models](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/3D%20Models/IFC%20Testing/IFC%20Parameters/BB%20Digital)
I had uploaded a few IFC models for testing, here is my feedback:

- Missing some BIM Data
![IFC Data BIMVision](https://user-images.githubusercontent.com/19904513/118664281-3f2b5700-b7e9-11eb-9620-a62f98955570.jpg)
![IFC Data BIMVision 2](https://user-images.githubusercontent.com/19904513/118664292-40f51a80-b7e9-11eb-8d2f-26fa284f52cc.jpg)
![IFC Data BIMVision 3](https://user-images.githubusercontent.com/19904513/118665596-54ed4c00-b7ea-11eb-9128-0ad972e72e94.jpg)

- Unnecessary use of colon twice. 
- Hard to read text, some parameter names are a nightmare to make out.
- Model Units are stuck to the Parameter name. Leave a gap and apply the bold text to make it easier to distinguish & see the parameter units.  Building(mm) > Building (**mm**)

The same applies to parameter name layers. Instead of the following:
_ArchiCADQuantities::N
et Surface Area of the Top(m²)_

Make it more like this:
_**ArchiCADQuantities**:
Net Surface Area of the Top (**m²**)_

![image](https://user-images.githubusercontent.com/19904513/118665006-d98b9a80-b7e9-11eb-9b03-f64922713de3.png)

**Comment by mosment3DRepo** [comment]
@carmenfan is there a reason we get certain IFCPROPERTYSETs and not others.

In Bogdan's example (model UWDAC-BBA-Z0-ZZ-M3-A-1005-P16.ifc) both "BBA_Pset_General::RequiredForCOBieComponent" and "BBA_Pset_TypeGeneral::RequiredForCOBieType" are defined as IFCPROPERTYSINGLEVALUE inside an IFCPROPERTYSET. Yet it only seems to be picking up the ones in the "BBA_Pset_Genera" property set

![image](https://user-images.githubusercontent.com/62879582/119669633-1bdb5a00-be30-11eb-87af-12f7f6186385.png)

**Comment by carmenfan** [comment]
> @carmenfan is there a reason we get certain IFCPROPERTYSETs and not others.
> 
> In Bogdan's example (model UWDAC-BBA-Z0-ZZ-M3-A-1005-P16.ifc) both "BBA_Pset_General::RequiredForCOBieComponent" and "BBA_Pset_TypeGeneral::RequiredForCOBieType" are defined as IFCPROPERTYSINGLEVALUE inside an IFCPROPERTYSET. Yet it only seems to be picking up the ones in the "BBA_Pset_Genera" property set
> 
> ![image](https://user-images.githubusercontent.com/62879582/119669633-1bdb5a00-be30-11eb-87af-12f7f6186385.png)

(We had this chat in teams already, just noting it down for future references)

The reason why these are not available on our metadata is because they are property sets of the Type. E.g. for a `IfcCovering`, these property sets are owned by a certain `IfcCoveringType` definition.

`IfcCoveringType` is linked up to an `IfcCovering` through a `IfcRelDefinesByType`. Which isn't just a straight forward parent child relationship, so we needed to treat it as a special cave and extract the relating type out to ultimately obtain the property sets information

This is now addressed as per [this commit](https://github.com/3drepo/3drepobouncer/commit/4ce75c5ed99e8b80be7e6b5cc9886a95d279d81a)

**Comment by carmenfan** [comment]
@BDavydov @mosment3DRepo 

This branch is ready for another look.

Just to sync up the expectations:
- **Missing BIM Metadata**
     -  All the missing data on the properties tab should now appear
     - Classification data should also look the same as BIMVision
     - The extra location/geometry data is out of scope as per the issue description in the bouncer issue: 
![image](https://user-images.githubusercontent.com/11945337/119858142-181d0580-bf0c-11eb-9ca0-0cabcec2af4e.png)

- **Unnecessary use of colon twice.**
`::` is a delimiter to signify they're categories, if we use `:` instead we're likely to get false positives. Ultimately this will be pretty much hidden from the user when this issue is implemented: https://github.com/3drepo/3drepo.io/issues/2629

- **Hard to read text, some parameter names are a nightmare to make out.**
This will be addressed in https://github.com/3drepo/3drepo.io/issues/2629. 

- **Model Units are stuck to the Parameter name. Leave a gap and apply the bold text to make it easier to distinguish & see the parameter units. Building(mm) > Building (mm)**
There's now a space between the units and the label. We can't really add bold for the units as we don't know it's units (at the point of reaching the database, it's just a string with everything). The only way we can bold them is if we just do a regex to bound anything that is within a bracket at the end of a metadata label, which will result in false positives.
