### ISSUE TITLE
Issue/SafetiBase reports are missing images

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2653]
### Description

Rather often when a user clicks on the Create Report button, they're presented with a PDF report template that's missing screenshot images. 

- This is happening in: prod
- This requires a hotfix to production: no 
### Steps to replicate
- Open any model in 3D Repo
- Open the Issues/Risks Panel
- Click on the options menu
- Click on the Create Report icon

### Current Behaviour
- PDF report with no issue/risks screenshots

### Expected Behaviour
- Include Issue/Risks Screenshots

### Pictures/ Gifs of the error
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/19904513/123414937-6cb7ad00-d5ac-11eb-8ead-886a3600af15.png)

**Comment by mosment3DRepo** [comment]
Intercom issue: https://app.intercom.com/a/apps/hrs24f1r/inbox/inbox/4437208/conversations/8867

**Comment by carmenfan** [comment]
@ChristosTsiotsias has figured out why. This is related to the referrer check we introduced in #2449 

In this instance, the user has logged in via 3drepo.io, so the session is stored against `http://www.3drepo.io/`

When we generate the report, the referrer is actually the API endpoint. Due to backwards compatibility for external applications, we've retained a round robin of api endpoints (`https://www.3drepo.io`, `https://api1.www.3drepo.io`, `https://api2.www.3drepo.io`, `https://api3.www.3drepo.io`, etc). So if the images are using `http://www.3drepo.io/` then it'd display, but if one of the other API domains are used then session check would return false.
