### ISSUE TITLE
Floating Panels

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2659]
### Description

Currently many of the features in 3D Repo are not easy to use when 2 cards are shown at once, due to the header and footer and large amount of content in the card

#### Must Have

- [ ] Allow users to drag cards out of the left hand div
- [ ] Automatically resize remaining panel to the full height of the div
- [ ] Allow the cards to expand and collapse by clicking an icon in the header to allow cards to be configured but collapsed to see more of the model
- [ ] Allow vertical resizing of the cards (horizontal could be dangerous due to formatting issues)
- [ ] Allow the left hand icon buttons to control the visibility of the cards in the same way it does now

#### Nice to have
- [ ] Allow cards to "snap" back into the div (nice to have) 
- [ ] If 2 cards are already present in the left hand div and the user opens another, it should appear as a floating card to the right of the existing cards
- [ ] If a floating card is closed (using the left hand buttons) and then reopened, it should remember it's previous floating position

### Related Resources

**Allow users to drag cards out of the left hand div**

https://user-images.githubusercontent.com/62879582/123796702-4dd35680-d8dd-11eb-8489-d90bedc1626c.mov

**Allow the cards to expand and collapse by clicking an icon in the header to allow cards to be configured but collapsed to see more of the model**

https://user-images.githubusercontent.com/62879582/123796749-59268200-d8dd-11eb-9041-c703606ee1e6.mov

**Allow vertical resizing of the cards (horizontal could be dangerous due to formatting issues)**

https://user-images.githubusercontent.com/62879582/123796530-1f557b80-d8dd-11eb-8880-07c0734a329e.mov

**Comment by carmenfan** [comment]
@mosment3DRepo 

questions:
1. What do you expect to happen when you open the first card? Should it take the full height right now?
2. If yes to 1., does that mean you still want the functionality to cut to half width on the 2nd card?
3. If 2, what happens if I've resized the card to be smaller than half width?
4. What's the point of collapse/expanding when the user can show/hide the card by pressing the buttons on the left panel?
5. I think it shouldn't be too hard to fix horizontal formatting if we want to make it adjustable horizontally. (@sanmont3drepo  might want to confirm this.. it should just be some small adjustment to css?)

Personally I think we should just give up the idea of having a dockable left div. every card spawns at the default position (where it currently is), and can just go on top of each other. The user can just move it to where ever they want. Then we won't have to worry about question 1, 2, 3, which requires extra little logic here and there that is prone to error.

**Comment by sanmont3drepo** [comment]
I think this is a quite expensive to do. It all depends how much time we want to spend on this.  If we implement this design as it is we wouldn't be able to reuse the component used in the legends card and we'll have to develop a layout system.
I can put on a small demo and see if it actually solves the problem.

Again, we can implement this as it is but instead of one day it would be a couple of weeks (a week first version and another week to debug).

**Comment by carmenfan** [comment]
closing as we don't want to do it anymore
