### ISSUE TITLE
Teamspace admin can't assign users permissions to a select few models

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2805]
### Description
API request to update a user permission fails if the existing permission array consist of a user that doesn't exist/no longer in the teamspace

### Steps to replicate
- go to the model settings of the model in the database
- Add a new permission entry for a user that doesn't exist
- try to update the permissions of that model (e.g. add an existing user into the model as a collaborator)

### Current Behaviour
- API request fails with USER_NOT_FOUND

### Expected Behaviour
- API request should pass.

<details>
  <summary>Bogdan's Original bug report</summary>

### Description

I open the User management panel and head over to model & federations permissions of a particular project. Most of the models are working fine. However, there are 2 models that won't allow you to change user permissions. It throws an error message "User Not Found"

- This is happening in: prod
- This requires a hotfix to production: yes

### Steps to replicate
- Open the [User Management window](https://www.3drepo.io/dashboard/user-management/John_Sisk_TeamSpace/projects?project=Project%20Kells&view=1)
- Select models 21.9.27 or Main 4D Model
- Change the permission level for any of the users
- Get an error message

### Current Behaviour
- Only works with some models

### Expected Behaviour
- Expect the model permissions to work across all of the models

### Pictures/ Gifs of the error
[User Management Issue](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Images/Sisk%20User%20Permissions.png)

**Warning Message**
![image](https://user-images.githubusercontent.com/19904513/135450343-ab8747f3-b0be-430a-8938-561635a5b232.png)

</details>

**Comment by carmenfan** [comment]
This is happening due to an inconsistency with the data.

There are 3 models within this teamspace, where a user has been assigned some permissions but they are no longer a member of the teamspace. And even though the endpoint request only requested to change one person's permission, the logic on the backend is updating the entire array (and checking everyone within the permissions array is a member of teamspace, hence the error message)

So 2 problems here:
- For some reason the database isn't being cleaned up completely when someone is removed from the teamspace
- We should only update the permission entry of the person of interest, not anyone else.

**Comment by carmenfan** [comment]
@mosment3DRepo  putting this in product triage,

But bear in mind that we'd rewrite this when we port it to v5 (also the possibility of permissions revamp) - so not sure if it's worth spending time on.
