### ISSUE TITLE
Enable touch navigation on Android & iOS

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2972]
### Description

Currently touch navigation on an android device is ineffective.

It seems when rotating with a single finger the pivot point is always set to a predefined location, the same appears to happen with zooming with a pinch.

### Goals

- [ ] Single touch to navigate the model
- [ ] Pinch to zoom
- [ ] 2 finger touch to pan
- [ ] Pivot point should be located on the initial touch point, or between 2 fingers if it is a zoom

https://user-images.githubusercontent.com/62879582/150984266-e7e19821-ef0d-4333-bab3-6df8d66ee6b5.mp4

**Comment by carmenfan** [comment]
#### Ipad observations:

##### prod/staging
- Loading a model of ~600MB, we already run into unity memory errors
- warning about mobile browser no longer show up on staging
- Chrome doesn't seem to work, but firefox does.
- (firefox) On toy project federation - model is stuck on loading state and only loaded the first submodel (architecture). so geometry is missing and the UI wouldn't let me add issues as it thinks the model is still loading
- Generally flakey, - unity crashes with abort(61) when i try to highlight something, but after a few refresh everything worked fine.
- navigation works as intended:
  - single finger for orbiting (just need to fix the pivot point to finger position instead of lookat vector)
  - 2 finger for pannig
  - 3 finger/pinch for zooming in and out


##### Streaming branch
- Loading a large model in the streaming branch will also result in memory error (ISSUE-3065)
- Loading a large model in streaming branch, restricting the memory threshold to 200/200, unity still fails with out of memory
- loading a small model that loads in staging/prod, the model doesn't show up

**Comment by keifgwinn** [comment]
Which iPad is this?, they do increase the memory quite a lot over various generations

**Comment by carmenfan** [comment]
@keifgwinn  the one jozef bought years back.
MQDT2B/A

**Comment by sebjf** [comment]
**Android Observations**
(Android 12; Chrome 108.0.5359)

- [ ] Unity shows a black screen in Portrait Mode
- [ ] Tapping on items usually results in model rotating (though interestingly, the items under the touch event are selected, so its not that it thinks all touch events are in the middle of the screen)
- [ ] Pivot point is always at 0,0,0
- [ ] Touch events reset the rotation to some odd value underneath the model
- [ ] Multiple touch events jump the zoom to an odd value

Creating a simple input emulator, I can reproduce at least some of these with just one touch event (emulated by the mouse), so they are at least in part Unity issues. I have created a new issue for the Unity specifics: https://github.com/3drepo/3drepounity/issues/441

Streaming

`setStreamingMemoryThreshold` is like setting the 'reserved amount', so to limit the total memory to something like 200 Mb, it should be set to, e.g. 1800. (`setStreamingMemoryLimit` is more as it sounds and only applies to the geometry.)

I would expect on large models milestone 1 will OOM due to the metadata before it even tries loading. Unfortunately 434 was broken by the big merge of 422 updates (I had a brief go at getting it up to test under 3794 but not too far) so there is no working milestone 2 branch at the moment to test this.

**Comment by sebjf** [comment]
Hi @carmenfan, 

To confirm

> 3 finger/pinch for zooming in and out

You mean holding two fingers stationary, then moving the third to zoom? (As opposed to, e.g. iOS's double three finger tap to zoom by a set amount, etc)

**Comment by carmenfan** [comment]
> Hi @carmenfan,
> 
> To confirm
> 
> > 3 finger/pinch for zooming in and out
> 
> You mean holding two fingers stationary, then moving the third to zoom? (As opposed to, e.g. iOS's double three finger tap to zoom by a set amount, etc)

(I think) I meant putting 3 fingers down and move them all at the same time, or pinching with 2 fingers

**Comment by sebjf** [comment]
> (I think) I meant putting 3 fingers down and move them all at the same time, or pinching with 2 fingers

Got it! (And that works on Android too)

**Comment by sebjf** [comment]
Hi @carmenfan,

Quick question: should the three finger zoom zoom to the location in front of the camera, or the geometric centre of where the users place their fingers (like for the pinch zoom)?

**Comment by carmenfan** [comment]
> Hi @carmenfan,
> 
> Quick question: should the three finger zoom zoom to the location in front of the camera, or the geometric centre of where the users place their fingers (like for the pinch zoom)?

tbh I don't even know if we want this anymore. @mosment3DRepo ?

**Comment by mosment3DRepo** [comment]
> Hi @carmenfan,
> 
> Quick question: should the three finger zoom zoom to the location in front of the camera, or the geometric centre of where the users place their fingers (like for the pinch zoom)?

I think it should do a zoom to the centre point of the camera, like you say if you want do zoom on a specific point you would do a pinch zoom
