### ISSUE TITLE
Can't drag select on certain models

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3982]
### Description

Holding shift and dragging the mouse does not perform a selection on certain models

- This is happening in: prod
- This requires a hotfix to production: yes

### Steps to replicate
- Open the model link in this [Dropbox Folder](https://www.dropbox.com/scl/fo/a7h33n7qtjwpxe9jhu25f/h?dl=0&rlkey=e5hgn3urx9ye3gmoawuhwkibf)
- Login with support credentials
- Try to do an object selection using shift+click & drag

### Pictures/ Gifs of the error
Video in [Dropbox Folder](https://www.dropbox.com/scl/fo/a7h33n7qtjwpxe9jhu25f/h?dl=0&rlkey=e5hgn3urx9ye3gmoawuhwkibf)

**Comment by carmenfan** [comment]
this is unity related 
![image](https://user-images.githubusercontent.com/11945337/219377303-217386b5-aa8d-4ffe-a4a1-706d7140abcd.png)

**Comment by carmenfan** [comment]
![image](https://user-images.githubusercontent.com/11945337/219617092-c9fbab11-564b-49f0-8ad9-44940e7589d4.png)

this is happening during rectangular select

**Comment by sebjf** [comment]
This exception occurs during the narrowphase of the selection tool.

The selection tool has two steps: 

In the broadphase it checks the bounding boxes of each submesh against the frustum defined by the rectangle in screen space. It does this by performing tests on the GPU, and writing the results to a texture. The data structures for these tests (per submesh bounds) are created when the json mappings are loaded.

In the narrowphase, each potentially intersecting submesh is rendered to a false colour target and then this is used to perform a pixel-perfect selection test.

Under Streaming Milestone 1, all mappings are loaded ahead of time, but the graphics meshes (Bundles) are loaded on demand. This means submeshes can pass the broadphase, but the narrowphase will encounter an error.

The fix for the exception is simply to check if the supermesh is loaded or not before attempting to access it. However, this will cause confusing behaviour in the measure tool:

 - If users select a region where only some submeshes are loaded, the broadphase will automatically select all submeshes that fall entirely within the rectangle, whether they are loaded or not.
 - Additionally, loaded submeshes will pass the narrowphase
 - Only those *not* loaded and *half* under the rectangle will not be selected.
 - Meaning if the user were performing a highlight, for example, if they were to shift the camera afterwards they may get a bunch of submeshes load in, half of which are selected and half of which aren't.

A possibly better fix would be to update the end of the broadphase. All intersecting and potentially intersecting submesh Ids would be filtered and only those whose Bundles are fully loaded would be allowed to pass. This would mean users can only select items that are on-screen/fully loaded at the time the selection is made.

What do you think @mosment3DRepo?

**Comment by carmenfan** [comment]
merged into #3887
