### ISSUE TITLE
Release candidate for 5.2.0

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4137]
Snapshotting staging to create a release candidate for 5.2.0 so we can start the QA process

**Comment by The-Daniel** [comment]
#### Description
In the Kanban board (and probably also viewer) Commenters that are unassigned to an issue/risk and therefore cannot edit the fields can still add/edit the image.  Other fields allow you interact with them but will give you a permissions error modal (some of this also applies to viewers)

Commenters:
- The due date is not disabled. Changing it gives an error modal, however the field appears as though it has changed
![image](https://user-images.githubusercontent.com/62481250/227934071-89272fc2-ceba-4fe3-bdc3-4ed6dae7de54.png)
- 4D fields and attachments can be changed (this might be desired behaviour)
- Commenters seem to have full permissions on risks even if they have not been assigned as risk owner. Is this desired behaviour?

Viewers:
- The 'Add image' button is not disabled. Upon adding an image you get a permissions error
![image](https://user-images.githubusercontent.com/62481250/227935955-7f7d784c-99b2-4172-b959-9903c68b3f14.png)
- Same due date not disabled bug listed above
- 4D fields can be interacted with. Permissions error modal upon change
- (Risks) The add resource button is there but cannot be interacted. Perhaps it'd be best to hide this button?
![image](https://user-images.githubusercontent.com/62481250/227936608-4e9c2621-ca84-4a49-8eb5-3f749353c5c0.png)
- (Issues) The add resource button is there and _can_ be interacted with. Upon submitting the user gets two error modals
![image](https://user-images.githubusercontent.com/62481250/227938146-f3d201c0-6588-4735-9ec0-4466a95bc6ea.png)
![image](https://user-images.githubusercontent.com/62481250/227937944-5a114580-312a-4c2e-8dd4-0c2472848801.png)
(I think it might be one for resources and another for links)
- It looks like the add image button for comments is not disabled. The button is disabled
![image](https://user-images.githubusercontent.com/62481250/227936513-a4574703-75b1-4260-8043-415330f397a7.png)

#### Pictures/ Gifs of the error

Changing the image (notice other fields are disabled)
![image](https://user-images.githubusercontent.com/62481250/227933792-c0eda7ab-2410-4e54-bd29-1a69abb9091e.png)
![image](https://user-images.githubusercontent.com/62481250/227933872-304c94de-7ebe-48e0-90ad-719f7f288ae9.png)

**Comment by The-Daniel** [comment]
#### Description
When clicking to view a small image in a risk/issue the modal header is weirdly unattached from the image. I think perhaps the image should have a min-size that's the same as the modal header. Also the image can end up being smaller than from before you clicked it which kind of makes the view image functionality a bit pointless.
The header says 'Screenshot' even though it can be an uploaded image instead of a screenshot

#### Steps to replicate
In an issue or risk set the image to be one that has small dimensions

#### Pictures/ Gifs of the error

![image](https://user-images.githubusercontent.com/62481250/227941622-4a94a678-9442-441e-84d9-6c5fd695ded5.png)

**Comment by sanmont3drepo** [comment]
#### Description
When opening the compare card in a container the container is not selected in the list

#### Pictures/ Gifs of the error
<img width="402" alt="image" src="https://user-images.githubusercontent.com/42032433/227943338-7ad3cb9e-ccd8-4373-902f-cb35a978c9e7.png">

**Comment by sanmont3drepo** [comment]
#### Description
When filtering a model, deselect action deselects all models instead of the selected one

#### Steps to replicate
 - Go to a federation
 - Filter one model
- Click on deselect

#### Current Behaviour
- Deselects all models

#### Expected Behaviour
- Deselects the selected model

#### Pictures/ Gifs of the error
![deselection error](https://user-images.githubusercontent.com/42032433/227944748-37160bd9-33c9-4bf7-b678-5df56f816a64.gif)
