### ISSUE TITLE
Series of bugs around creating issues

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#415]
- [x] Sometimes issues don't load and you can't add new issues (button is greyed out)
- [x] The Issues tab is 285px fixed height 
- [x] Buttons only appear when a title is given
- [x] Behaviour is not consistent across editing and creating

Also some other problems I will add later

**Comment by carmenfan** [comment]
While you're at it, can you fix the viewpoint bug that's always been there?
Basically, there are 4 ways to trigger the viewpoint to set to the issue's viewpoint:
* Clicking on the issue on the issue list
* Clicking on the pin associated with the issue
* Clicking on the arrow when the issue is highlighted on the issue list
* Clicking on the issue description

They should all behave the same, i.e.
- Go to the viewpoint
- Set clipping plane (if there is one)
- Highlight pin (i.e. colour of pin changes from red to yellow)
- Highlight objects associated with the issue

I've fixed most of it whilst migrating to unity, only one i left was clicking on the issue description doesn't highlight objects associated with the issue, as there was no way to retrieve the info within that component. 

I'd imagine everything should naturally fall into place once you've rewrote/refactored this, but just bear it in mind :)

**Comment by JamesMilnerUK** [comment]
This should be okay now :) Let me know how you get on @carmenfan @paloknapo
