### ISSUE TITLE
Account json files take a while to download

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#456]
Is there anyway we can look into improving the performance of this? At the moment some of the big account json files can take 800ms+. Perhaps we can do some caching / optimisations of some sort?

The problem is that the data is required for a lot of the UI to finish loading, making the app feel a little janky.

**Comment by JamesMilnerUK** [comment]
Here is an example over a 3G+ connection: 

![screenshot_20170812_145609](https://user-images.githubusercontent.com/8822075/29241292-7b5b6aba-7f6e-11e7-98d6-b08f3f774bb7.png)

**Comment by carmenfan** [comment]
There's not a lot of reason for it to fetch every single teamspace/project/model information in a single fetch. the best way to do this is to break it down into multiple apis. ideally, the first api should just give you the list of teamspace that is available to the user, then we can have an api per team space (which you won't even need to call if the user never expand that teamspace or call it asychonrously in the background whilst the user can see some proggress.

The other thing that would make the db query run a lot faster is if we rework the data model to be user oriented instead of resource orientated, as the search is always based on username, a data structure that utilise the username as index would make it run so much faster.

Could look into this, but def not a 1.13 thing i think. It once again causes too many breaking changes. Also not that pressing as most users would have less projects/model access that what my account have on dev. So this is one of the worst case scenarios
