### ISSUE TITLE
Add hotjar for prod

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4569]
### Description
Adding the code snippet from _Hotjar_ so the  the Product Team can get insights into user behaviour to help validate design decisions.

### Tasks
- [ ] Research how to integrate hotjar in https://www.hotjar.com/
- [ ] Integrate and test hotjar

### NOTES:
- It should be configurable whether hotjar is applied to the deployment (We don't want to do it for local/staging etc)
- Hotjar id should come from the configuration file so it can be changed without code level changes.

**Comment by keifgwinn** [comment]
FYI hotjar is included in the uBblock Origin extension that's quite popular.

**Comment by AsiteZane** [comment]
@Charence - probably need to see what we have on Google Analytics already, best we keep this on hold though as more pressing things coming through

**Comment by carmenfan** [comment]
Google analytics doesn't track hot spots on the UI as far as I know? GA is more of a marketing tool, this is more of a product tool


This should be relatively simple to add and free to use so it's probably easiest to determine value after we got some data


I would suggest we keep going with this as planned unless there's a roadblock.


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AsiteZane** [comment]
@carmenfan / @Charence 

If it helps, I'm particularly interested if we can get this implemented effectively for 3drepo.io, and not 3drepo.com - interested in recordings, feedback. Surveys might be interesting in the future but not right now and certainly not with the scale of users we have.

Would also be good to run this on our help pages with heatmaps and feedback functionality to see what people are generally reading.

**Comment by carmenfan** [comment]
@AsiteZane  the basis is done for 3drepo.io - but due to it being a single page application we may have to add extra hooks to make it meaningful.

But to prevent unnecessary work I've told @Amantini1997 to just keep it as the basic version and we'll try it out - and if it's proven meaningful but we need extra details we can look at it again.

I'm not sure if we can do this on help pages as that's managed by intercom, it requires us adding code in the application (none of the tech team have access)
