### ISSUE TITLE
Custom Ticket: Clicking on the viewer background deselects ticket, but leaves view on

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4709]
### Description
- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- In the viewer, from the tickets list, select a ticket (without expanding it) that has a default view with some groups (you should see some meshes being coloured)
- click on the viewer background

### Current Behaviour
The ticket is deselected (the background of the ticket item is white instead of grey), but the overrides are all still there until you click on the background of the ticket list

### Expected Behaviour
Either:
- the ticket should not be deselected, or
- the ticket should be deselected and the viewpoint it generated should be cleared

### Pictures/ Gifs of the error

https://github.com/3drepo/3drepo.io/assets/43547703/ef52072b-90e3-4b64-825e-f421048d4c16

**Comment by carmenfan** [comment]
@Amantini1997  what do you expect it to happen? I'm a bit lost.

It shouldn't reset the view if that's what you're thinking.

**Comment by carmenfan** [comment]
view is not a state but a snapshot, so there should be no concept of reset - exiting a ticket should not unhide/uncolour/untransform any geometry. This will be very off-putting to the user, especially if they're trying to create a new ticket based on an existing one.

as discussed with @sanmont3drepo this will be fixed in #4642 thus i think we can close this? Reopen with comment if i'm mistakened.
