### ISSUE TITLE
Graphics issue when using measuring tool and adding pins (issue, SaftiBase, ticket)

### ISSUE THREAD

**Issue by jamie-iskander** [3drepo/3drepo.io#4790]
### Description

On high performance laptops there is an issue when using the measuring tool or when adding pins. 

- This is happening in: prod 
- This requires a hotfix to production: tbc 

### Steps to replicate
- Open any model on user's laptop..  (DM @jamie-iskander  for their name)
- Add pin or add measuring tool. 

### Current Behaviour
- Expect to see a single line on the measuring tool or a single pin. 

### Expected Behaviour
- All models should be highlighted

### Pictures/ Gifs of the error

![image](https://github.com/3drepo/3drepo.io/assets/126164675/18e62340-46bc-4f04-a781-a150c9391dd1)
![image](https://github.com/3drepo/3drepo.io/assets/126164675/8d93e556-1612-4733-851f-1ac78bcbb8c4)

**Comment by carmenfan** [comment]
@AsiteZane  we've seen this before on Mia's laptop, but could not reproduce on anyone elses'....

It's a bit difficult for @sebjf  to look into the reason why when we don't have a reliable way to reproduce... unless @sebjf have any further ideas

**Comment by carmenfan** [comment]
> @AsiteZane we've seen this before on Mia's laptop, but could not reproduce on anyone elses'....
> 
> It's a bit difficult for @sebjf to look into the reason why when we don't have a reliable way to reproduce... unless @sebjf have any further ideas

@sebjf  could it be to do with pause rendering being a be unpredictable? sound we be turning it off when we're in an action like this?

**Comment by sebjf** [comment]
I am wondering if it's the same as this issue: https://github.com/3drepo/3drepounity/issues/495

Is it possible to check the model of GPU(s) on the problem machine, and possibly [switch the high performance one](https://github.com/3drepo/3drepounity/issues/495#issuecomment-1845114139) on or off?

**Comment by AsiteZane** [comment]
@sebjf / @carmenfan  I hopefully have a call with him tomorrow to resolve this to see if the GPU(s) are causing the issue. I'll let you know how it goes.

**Comment by AsiteZane** [comment]
@sebjf / @carmenfan So, sad news, he only has one GPU and it's the onboard Iris GPU which I was having issues with. I'll get him to send the about GPU report and Console log so we can dig a bit deeper. I wouldn't be surprised if this happens to other customers. We seem to have an issue with these onboard graphics GPUs. He's always in the office so if you wanted to triage aggressively in-person Sebastian, that's always an option.

**Comment by AsiteZane** [comment]
@sebjf / @carmenfan - info below whenever you think it is appropriate to look at it.

[www.3drepo.io-1709306894780.log](https://github.com/3drepo/3drepo.io/files/14463010/www.3drepo.io-1709306894780.log)
![webGL report](https://github.com/3drepo/3drepo.io/assets/148439628/d67ca890-ded1-4903-88ff-2b348f57e562)
[about-gpu-2024-03-01T15-25-50-425Z.txt](https://github.com/3drepo/3drepo.io/files/14463013/about-gpu-2024-03-01T15-25-50-425Z.txt)

**Comment by carmenfan** [comment]
@sebjf  if you can quickly sanity check to see anything obvious?

Beyond that I think we'd need a laptop that can reproduce this to thoroughly investigate

**Comment by sebjf** [comment]
Hi @carmenfan @AsiteZane yes this confirms the GPU is the same as the model we've had previous issues with. There isn't any indication of why changing RTs (if that is the problem) fails. (The screenshot is of the WebGL 1.0 info but I am guessing Web GL 2.0 is substantially similar, since the viewer shouldn't load without 2.0 support nowadays.)

If the issue is as expected, turning off Pause Rendering should fix it. That's not exposed in the Viewer Settings, but we could make a staging deployment to test it on?

**Comment by carmenfan** [comment]
@sebjf we had the pause/resume rendering functions exposed in UnityUtils ages ago for debugging purpose https://github.com/3drepo/3drepo.io/blob/master/frontend/src/globals/unity-util.ts#L1548

Do they still work? perhaps we can use it as a quick test

**Comment by sebjf** [comment]
> Do they still work? perhaps we can use it as a quick test

Unfortunately not - it just forces pausing on regardless of input, so the opposite of what we need!

**Comment by sebjf** [comment]
Hi @carmenfan @AsiteZane, I was about to add the new API when I found we *do* have one, its just both @carmenfan and I were looking at the wrong one!

The unfortunately-named-in-retrospect `UnityUtil.toggleCameraPause()` can be used to toggle the render pause/caching on and off.

(This is still not exposed via the settings dialog, but Kieran can use this in the Console to see if it is a viable workaround.)

**Comment by AsiteZane** [comment]
> Hi @carmenfan @AsiteZane, I was about to add the new API when I found we _do_ have one, its just both @carmenfan and I were looking at the wrong one!
> 
> The unfortunately-named-in-retrospect `UnityUtil.toggleCameraPause()` can be used to toggle the render pause/caching on and off.
> 
> (This is still not exposed via the settings dialog, but Kieran can use this in the Console to see if it is a viable workaround.)

@sebjf , thank you. How would you do that via the console? I've tried looking around with limited success sorry.

**Comment by sebjf** [comment]
Hi @AsiteZane, thats correct - unless you mean you give the command and then it responds twice?

What you should see is that calling it changes the reported value:

![image](https://github.com/3drepo/3drepo.io/assets/5058369/fa9be485-1edc-43c3-ad97-4eb86676a0ea)

The default is On, which means the render caching is enabled. Calling it once should turn it off. On larger models you should see a drop in FPS when it's Off.

**Comment by AsiteZane** [comment]
Hi @sebjf , what I mean is it keeps turning it on and off without stopping...

**Comment by carmenfan** [comment]
> > Hi @carmenfan @AsiteZane, I was about to add the new API when I found we _do_ have one, its just both @carmenfan and I were looking at the wrong one!
> > The unfortunately-named-in-retrospect `UnityUtil.toggleCameraPause()` can be used to toggle the render pause/caching on and off.
> > (This is still not exposed via the settings dialog, but Kieran can use this in the Console to see if it is a viable workaround.)
> 
> @sebjf , thank you. How would you do that via the console? I've tried looking around with limited success sorry. Screen shot below - i was trying to create a live expression but that doesn't seem to work... keeps looping between false and true ![image](https://private-user-images.githubusercontent.com/148439628/312995332-355c5aff-f0ad-4950-a003-6d3e92129431.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDkyNDQsIm5iZiI6MTcxMDUwODk0NCwicGF0aCI6Ii8xNDg0Mzk2MjgvMzEyOTk1MzMyLTM1NWM1YWZmLWYwYWQtNDk1MC1hMDAzLTZkM2U5MjEyOTQzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQxMzIyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDYyMzBjOWRhYTk1ZDk2Y2U5MjhlYjk5MDFiNzhkMDdiNWMyOTQ1Yzg1ODZiNGVkZDc1OGY0ZTg4ODJlMGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aH641dlN-S6oGPnofa80G8CkXPj4ATxcom434tNzrtQ)

@AsiteZane  don't create a live expression 🙈 

just go onto the console and type it in once.

By doing a live expression you're basically calling the function over and over again 😆

**Comment by AsiteZane** [comment]
@sebjf / @carmenfan  Whoopsie... went for the most complicated way to address a simple problem 😓 

News back from the naughty laptop and their user - great success! UnityUtil.toggleCameraPause() works a treat, is there any way to force it off client-slide when loading a 3DR session so they don't have to do it for each session?

**Comment by carmenfan** [comment]
We could map it into the viewer settings, but that would refer a bit of front end effort.

@sebjf probably a better judge of this, but I don't think we want to permanently turn it off? we probably want to only turn it ogg when we're rendering an animation and during measurements... Otherwise there's going to be massive lag just operating the viewer when you're loading large models.

**Comment by carmenfan** [comment]
@AsiteZane aside from opening a session in advance put in the function call, there isn't much way around this without sneaking it into viewer settings.

There might be some browser extensions he can utilise to do it automatically https://stackoverflow.com/questions/22707808/automatically-run-javascript-code-upon-loading-a-specific-website#:~:text=You%20can%20use%20dotjs.,%2F%20%2C%20dotjs%20will%20execute%20~%2F.

**Comment by carmenfan** [comment]
@AsiteZane  but I do mean for this specific user, if he's demoing with it disabled, make sure he thoroughly check with models he intend to demo with that he's not experiencing lag due to turning this feature off. In the past it has become quite a problem in chunk models!

**Comment by sebjf** [comment]
As discussed in the meeting...

We have confirmed that a number of issues of this type can be solved by turning the Pause Rendering feature off, though the problem with doing this is that the viewer will take a performance hit, which will be especially noticeable during things like mark-up.

There are a number of possible next steps:

1. We have an IRIS XE laptop, so we could try and rework the rendering code around the actual bug in a general way. This is likely to take a long time and not guaranteed to work, though it fixes the issue for good.

2. The simplest workaround is for the sales team to [turn off Pause Rendering](https://github.com/3drepo/3drepo.io/issues/4790#issuecomment-1997404467) on demand. Possibly expressing this in the Visual Settings dialog. 

3. A middle approach is to build a compatibility shim into the viewer logic. When a flag is set, when any tool or feature that might be vulnerable to the bug is active, pause rendering is automatically disabled.

The value proposition for (3) is a little low at the moment, because no customers are reporting the issue, and there is no way to detect the GPU. We would not want to turn the shim on by default, and if no customers are reporting the issue for us to tell them to turn it on manually, the only beneficiaries of that development work are the Sales/CS team, whose problem could also be solved by using a different laptop.

**Comment by sebjf** [comment]
Some further investigation into this...

Tests with an Iris Xe confirm that the issue is that the main camera ends up drawing into the Scene Camera's Render Texture (RT) - not that, for example, the Front Buffer is not being cleared properly.

We can observe the behaviour of this by placing a RawImage Component on the Screen Canvas and setting its image to the Scene Camera's RT. This should give us a picture-in-picture of only what the Scene Camera's RT contains.

There are a few interesting things to note about this.

1. While all mesh objects, such as our lines and Pins, 'overdraw' this way, anything on the `UGUI.RenderingRenderOverlays` pass does not.
2. There is a temporal aspect, which is that after the Scene Camera draws to the buffer, it takes a frame or two for the 'main' camera to draw over it.
3. It is definitely that the main camera is drawing - not simply being cleared. As we can see the Main Camera's Skybox draw.

Various parts of the pipeline have been toggled, around the CameraRenderTextureChain CommandBuffers, and the RenderTextureManager on the Scene camera, but the behaviour doesn't change.

However, if we create a RenderTexture *asset*, and assign it to the Scene Camera & RawImage Component at design time, then the RT does not appear to be overridden and we get the expected picture-in-picture effect, with no overdraw of our UI elements.

![image](https://github.com/3drepo/3drepo.io/assets/5058369/f3d78056-4c0d-43e7-93e3-51c2d33c44e8)

Using this same RenderTexture in the previous graphics pipeline (with the Command Buffer Blit) also works. Assigning the RT *asset* dynamically in Start() and via the callbacks as before also works.

It appears then that the dynamically created RTs differ from the assets in some way the Iris XE is sensitive to...

(PS. this investigation has also stumbled upon [this](https://github.com/3drepo/3drepounity/issues/519), though there doesn't appear to be any relation yet.)

**Comment by sebjf** [comment]
Further testing shows its the size of the RT that causes the issue - the static RT has a different size than the front buffer. If a RT is created from the assets descriptor, then the bug does not show, but if the size of the asset's descriptor is updated beforehand, then the bug reveals itself.

This may have something to do with some sort of caching the driver is doing.

**Comment by sebjf** [comment]
Attempting to create an MWE in a new Unity project shows that it is possible to render to a texture like we intend on the Xe. Comparing the two projects reveals the issue is in the msaa settings of the RenderTexture. With msaa not set in the RenderTextureDescriptor, the bug does not manifest on the Iris Xe.

Looking further at this, it seems that the camera controls the MSAA and this no longer needs to be set on the RT for MSAA to work - the Scene Camera takes the setting from the Quality settings.

A Unity issue to make this change permanently has been created [here](https://github.com/3drepo/3drepounity/issues/520).

**Comment by sebjf** [comment]
@AsiteZane, this branch (https://issue-4790.dev.3drepo.io/v5/login) is ready for Ciaran to test when he has a sec!
