### ISSUE TITLE
Object highlights (selection) is delayed on issue click

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#480]
When selecting an issue, the model zooms to the right spot but the selection highlights take a very long time to show. If multiple objects have selection on, the delay is even longer without any visual feedback. My suspicion is that the system attempts to highlight all of the required meshes and only afterwards calls a redraw. Possible improvement is to force redraw on every single mesh being highlighted one at a time.

**Comment by carmenfan** [comment]
unless it is a massive group of objects, this is more likely to be because highlighted objects are stored separate to the issue, which requires a API to find the group, which then gives you a list of shared IDs, which needs to be turned into unique IDs.

Since your testing day you've identified that concurrency is not working well on the server, I think it is likely that the groups API is taking too long to respond.

**Comment by carmenfan** [comment]
Does this happen because your CPU is being hammered? Or does this happen with other people's laptops?

I'm going to say this is a non issue unless we get more evidence (also try with production)

**Comment by JamesMilnerUK** [comment]
Worth linking in this issue if it happens to be related #500
