### ISSUE TITLE
Generate preview thumbnails for projects

### ISSUE THREAD

**Issue by maciejgryka** [3drepo/3drepo.io#54]
We need to generate preview thumbnails for each project to be able to display them in the thumbnail view on the homepage and dashboard. I'm not sure what the best approach is here, but maybe something like:
- whenever a project is updated, run a background job to render the preview to a file and update the DB with the new image?
- if an image is missing use a placeholder
- alternatively, have a custom field somewhere to allow project owners to upload their own previews

**Comment by jozefdobos** [comment]
For the moment the simplest approach is to off-screen render the screenshot in the desktop GUI upon each commit (I'll code that in). In the long term, however, we shall use X3DOM to generate the images server-side so that they visually match the browser-based rendering. X3DOM has a built-in functionality to take screenshots, ideally to be somehow integrated into the Bouncer service.

**Comment by jozefdobos** [comment]
Maciek, can you add placeholders for the moment and some way for the client to cut the appropriate size out of given image as its aspect ratio might not match what your UI expects. Thanks!
