### ISSUE TITLE
Pins sometimes hide behind objects

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#552]
Is there a way we can move pins in the direction of the camera when they are created ever so slightly? Otherwise sometimes they hide behind the object and/or flicker.

![screenshot_20171025_114133](https://user-images.githubusercontent.com/8822075/31994705-8a1bdbe4-b979-11e7-86a9-3c5665f82861.png)

**Comment by carmenfan** [comment]
They are designed to be 2D billboards, thus they always face the camera. So when you create it, it's created with a single point given (where the bottom tip will go) and it'll be made to face the camera (in this case, it will effectively lie flat along the wall which is why it's ghosted and maybe flicker as it's effectively z fighting with the wall)

If we move it slightly forward then it no longer touches the plane and when you move it to a different angle it might be hovering mid air. Especially with the inaccuracy of the z buffer projection, it's also unknown how much you need to before it will really be slightly in front the wall.

Angular tells unity the position to drop the pin. To edge it forward unity will have to do something like  position - forward vector * factor when it does that, but you'd also want the pin to be saved there, you'd have to feed it back to angular the adjusted position so it saves with the issue. When you reload the model with all the pins, then the pins will be adjusted towards the default camera angle, which might push it behind the wall anyway when it gets to the issue camera angle...

Conclusion is it's possible but imo not worth the effort. I think in real use cases it's very unlikely someone will drop a pin like this.
