### ISSUE TITLE
Unity throws error if you're very zoomed out

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#887]
Recent experiences with my mouse have shown me the following error:

![spectacle m22269](https://user-images.githubusercontent.com/8822075/38609313-a2394f92-3d75-11e8-86d2-dc5f5e7d4d6d.png)

Doesn't seem to crash anything or have any ill effect but I think we were speaking about maybe capping maximum zoom extent?

**Comment by carmenfan** [comment]
This happens when your camera is so far out that the near/far clipping plane calculations goes a bit haywire as it's dependant on where abouts your model is in respective to your camera's position.

Capping the zoom extent is not really the best solution, as the distance from object to cap would vary depending on where your object is. (for e.g if the object is at the very back corner of your view you would want to allow a further distance as oppose to something that's already quite far forward.) Not to mention zooming is not always object dependant, with the right click drag or if you zoom from background you could zoom away from a random point in space.

We could potentally lock the zoom when it reaches somewhere like extent, but that would restrict the map tile generation, like it might restrict the user from seeing some near by tiles that might require him/her to move away from the model slightly.

All in all I think if you're scrolling so far it's a conscious decision, and with the extent button there's always something to go back to. I could get rid of the error by tweaking the near far plane calculation next time I revisit that code.

**Comment by Charence** [comment]
In James's case, it's not necessarily a conscious decision :-)

**Comment by carmenfan** [comment]
If that's the problem then I think the best solution would be to get him a new mouse 😆

**Comment by carmenfan** [comment]
Max zooming per frame is now limited to a certain percentage of the bounding box as of #978. Still doesn't stop you from free wheeling your mouse scroll and going really far (it'll get really far slower though), but I don't think we really want to impose anything in that situation. (if it's intentional, it's intentional, if it's a mistake, that's what the extent button is for)
