### ISSUE TITLE
PM2: worker.suicide is deprecated

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#969]
### Description
Another discovery whilst looking at the logs:
![image](https://user-images.githubusercontent.com/11945337/39813751-8e1a2606-5389-11e8-9618-f81fceb61b39.png)

**Comment by JamesMilnerUK** [comment]
https://github.com/Unitech/pm2/issues/2780 looks like i can be ignored and doesn't look like they want to fix it

**Comment by adrienv1520** [comment]
This issue is related to the Node version used.

*worker.suicide*, an alias for *worker.exitedAfterDisconnect* in Node cluster module (core), is a boolean property used to distinguish between voluntary and accidental exit. This property is deprecated since Node v6.0 and a deprecation warning is automatically emitted when accessing this property since Node v7.0.

A PM2 dependency, *fclone*, accesses this property when cloning a worker causing the deprecation warning. Indeed, this property is present until Node v8 but is not since Node v9. Using a Node version >= 9 removes these deprecation warnings.

In a conclusion, these warnings can be ignored as no side effects can be found using PM2 with a Node version <= 8 and there is no necessity to upgrade Node or PM2 versions.
